name: grficosuniversal
description: Aplicativo gerado via Isaac Studio
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2
  path_provider: ^2.1.2
  http: ^1.1.0
  geolocator: ^11.0.1
  flutter_blue_plus: ^1.31.0
  mobile_scanner: ^5.0.0
  flame: ^1.16.0
  flutter_unity_widget: ^2022.2.1
  flutter_launcher_icons: ^0.14.0
  url_launcher: ^6.3.0 
  
dev_dependencies:
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
